# file: monit/tasks/main.yml

- name: Make sure monit is installed
  package:
    name: monit
    state: latest
  notify:
    - restart monit

- name: Update the monit configuration (/etc/monit/monitrc)
  template:
    src: "etc/monit/monitrc.j2"
    dest: "/etc/monit/monitrc"
    mode: 0400
  notify:
    - restart monit

- name: Ensure default monit config files for are present
  template:
    src: "etc/monit/conf.d/{{item}}.conf.j2"
    dest: "/etc/monit/conf.d/{{item}}.conf"
  with_items:
    - rsyslog
    - cron
  notify:
    - reload monit

- name: Ensure custom monit configs are in place
  template:
    src: "etc/monit/conf.d/_custom_.conf.j2"
    dest: "/etc/monit/conf.d/{{ item.type }}_{{ item.name }}.conf"
    owner: root
    group: root
    mode: 0644
  with_flattened:
    - "{{ monit_checks }}"
  when: item.type is defined and item.name is defined
  notify:
    - reload monit

- name: Remove messages if queuing disabled
  file:
    path: "{{monit_eventqueue_directory}}/{{item}}"
    state: absent
  when: not monit_eventqueue_enable
  with_items: "{{ monit_queued_messages.stdout_lines | default([]) }}"
